### ISSUE TITLE
Change .Description to .Summary

### ISSUE THREAD

**Issue by tonycapone** [digitalcraftsman/hugo-type-theme#1]
Hey there. 

One suggestion:  Change `{{ .Description | markdownify }}` to 
`{{ .Summary }}` in [hugo-type-theme/layouts/partials/post-list.html](hugo-type-theme/layouts/partials/post-list.html) as [that is the variable Hugo stores excerpts ](http://gohugo.io/content/summaries/)in.

That's why excerpts don't show above the "read more" links in post list.

**Comment by digitalcraftsman** [comment]
Hi @tonycapone,

thanks for reporting this issue. It seems that I mistakenly used `.Summary` inconsistently across the theme. Since some users prefer to create custom preview I made a compromise of both worlds:

First, I check if a `description` variable is set in the frontmatter and is not empty. If that the case I use `{{ .Description | markdownify }}`. Otherwise the theme defaults to the automatically generated `{{ .Summary }}`.

Take a look at the diff: b973ee09ee2f1eee5bc0975641c92db0a85d550e

Best regards,
Digitalcraftsman

**Comment by tonycapone** [comment]
Thanks!
